define([], function() {
  return {
    "PropertyPaneDescription": "Nastavení správy majetku",
    "BasicGroupName": "Obecné",
    "DescriptionFieldLabel": "Popis",
    "AssetsListNameLabel": "Název seznamu majetku",
    "DeploymentsListNameLabel": "Název seznamu přidělení",
    "AssetsTab": "Majetek",
    "DeploymentsTab": "Přidělení",
    "RefreshButton": "Obnovit",
    "EditButton": "Upravit",
    "DeleteButton": "Smazat",
    "SaveButton": "Uložit",
    "CancelButton": "Zrušit",
    "SearchPlaceholder": "Hledat...",
    "NewAssetButton": "Nový majetek",
    "NewAsset": "Nový majetek",
    "EditAsset": "Upravit majetek",
    "ColumnAssetTitle": "Název",
    "ColumnCategory": "Kategorie",
    "ColumnSerialNumber": "Sériové číslo",
    "ColumnAssetStatus": "Stav",
    "ColumnActions": "Akce",
    "FieldAssetTitle": "Název",
    "FieldDescription": "Popis",
    "FieldCategory": "Kategorie",
    "FieldSerialNumber": "Sériové číslo",
    "FieldAssetStatus": "Stav",
    "DeleteAssetTitle": "Smazat majetek",
    "DeleteAssetMessage": "Opravdu chcete smazat tento majetek? Tuto akci nelze vzít zpět.",
    "NewDeploymentButton": "Nové přidělení",
    "NewDeployment": "Nové přidělení",
    "EditDeployment": "Upravit přidělení",
    "ColumnDeploymentTitle": "Název",
    "ColumnAsset": "Majetek",
    "ColumnDeployedTo": "Přiděleno komu",
    "ColumnDepartment": "Oddělení",
    "ColumnDeployedDate": "Datum přidělení",
    "ColumnReturnDate": "Datum vrácení",
    "FieldDeploymentTitle": "Název",
    "FieldAsset": "Majetek",
    "FieldDeployedTo": "Přiděleno komu",
    "FieldDepartment": "Oddělení",
    "FieldDeployedDate": "Datum přidělení",
    "FieldReturnDate": "Datum vrácení",
    "FieldNotes": "Poznámky",
    "DeleteDeploymentTitle": "Smazat přidělení",
    "DeleteDeploymentMessage": "Opravdu chcete smazat toto přidělení? Tuto akci nelze vzít zpět.",
    "LoadingMessage": "Načítám data...",
    "LoadingUserMessage": "Načítám profil uživatele...",
    "ErrorPrefix": "Chyba: ",
    "UserErrorPrefix": "Nepodařilo se načíst profil uživatele: ",
    "NoAssetsMessage": "Nebyl nalezen žádný majetek.",
    "NoDeploymentsMessage": "Nebyla nalezena žádná přidělení pro vaše oddělení."
  }
});
