define([], function() {
  return {
    "PropertyPaneDescription": "Nastavení helpdesk tiketů",
    "BasicGroupName": "Obecné",
    "DescriptionFieldLabel": "Popis",
    "ListNameFieldLabel": "Název seznamu",
    "SearchPlaceholder": "Hledat podle názvu, popisu nebo přiřazené osoby...",
    "RefreshButton": "Obnovit",
    "NewTicketButton": "Nový tiket",
    "EditButton": "Upravit",
    "DeleteButton": "Smazat",
    "SaveButton": "Uložit",
    "CancelButton": "Zrušit",
    "ColumnTitle": "Název",
    "ColumnStatus": "Stav",
    "ColumnPriority": "Priorita",
    "ColumnCategory": "Kategorie",
    "ColumnAssignedTo": "Přiřazeno",
    "ColumnActions": "Akce",
    "LoadingMessage": "Načítám tikety...",
    "ErrorPrefix": "Chyba při načítání tiketů: ",
    "NoResultsMessage": "Nebyly nalezeny žádné tikety.",
    "NewTicket": "Nový tiket",
    "EditTicket": "Upravit tiket",
    "FieldTitle": "Název",
    "FieldDescription": "Popis",
    "FieldStatus": "Stav",
    "FieldPriority": "Priorita",
    "FieldCategory": "Kategorie",
    "FieldAssignedTo": "Přiřazeno",
    "DeleteConfirmTitle": "Smazat tiket",
    "DeleteConfirmMessage": "Opravdu chcete smazat tento tiket? Tuto akci nelze vzít zpět."
  }
});
