define([], function() {
  return {
    "PropertyPaneDescription": "Helpdesk Tickets settings",
    "BasicGroupName": "General",
    "DescriptionFieldLabel": "Description",
    "ListNameFieldLabel": "List Name",
    "SearchPlaceholder": "Search by title, description, or assigned to...",
    "RefreshButton": "Refresh",
    "NewTicketButton": "New Ticket",
    "EditButton": "Edit",
    "DeleteButton": "Delete",
    "SaveButton": "Save",
    "CancelButton": "Cancel",
    "ColumnTitle": "Title",
    "ColumnStatus": "Status",
    "ColumnPriority": "Priority",
    "ColumnCategory": "Category",
    "ColumnAssignedTo": "Assigned To",
    "ColumnActions": "Actions",
    "LoadingMessage": "Loading tickets...",
    "ErrorPrefix": "Error loading tickets: ",
    "NoResultsMessage": "No tickets found.",
    "NewTicket": "New Ticket",
    "EditTicket": "Edit Ticket",
    "FieldTitle": "Title",
    "FieldDescription": "Description",
    "FieldStatus": "Status",
    "FieldPriority": "Priority",
    "FieldCategory": "Category",
    "FieldAssignedTo": "Assigned To",
    "DeleteConfirmTitle": "Delete Ticket",
    "DeleteConfirmMessage": "Are you sure you want to delete this ticket? This action cannot be undone."
  }
});
