define([], function() {
  return {
    "PropertyPaneDescription": "Assets Deployment settings",
    "BasicGroupName": "General",
    "DescriptionFieldLabel": "Description",
    "AssetsListNameLabel": "Assets List Name",
    "DeploymentsListNameLabel": "Deployments List Name",
    "AssetsTab": "Assets",
    "DeploymentsTab": "Deployments",
    "RefreshButton": "Refresh",
    "EditButton": "Edit",
    "DeleteButton": "Delete",
    "SaveButton": "Save",
    "CancelButton": "Cancel",
    "SearchPlaceholder": "Search...",
    "NewAssetButton": "New Asset",
    "NewAsset": "New Asset",
    "EditAsset": "Edit Asset",
    "ColumnAssetTitle": "Name",
    "ColumnCategory": "Category",
    "ColumnSerialNumber": "Serial Number",
    "ColumnAssetStatus": "Status",
    "ColumnActions": "Actions",
    "FieldAssetTitle": "Name",
    "FieldDescription": "Description",
    "FieldCategory": "Category",
    "FieldSerialNumber": "Serial Number",
    "FieldAssetStatus": "Status",
    "DeleteAssetTitle": "Delete Asset",
    "DeleteAssetMessage": "Are you sure you want to delete this asset? This action cannot be undone.",
    "NewDeploymentButton": "New Deployment",
    "NewDeployment": "New Deployment",
    "EditDeployment": "Edit Deployment",
    "ColumnDeploymentTitle": "Title",
    "ColumnAsset": "Asset",
    "ColumnDeployedTo": "Deployed To",
    "ColumnDepartment": "Department",
    "ColumnDeployedDate": "Deployed Date",
    "ColumnReturnDate": "Return Date",
    "FieldDeploymentTitle": "Title",
    "FieldAsset": "Asset",
    "FieldDeployedTo": "Deployed To",
    "FieldDepartment": "Department",
    "FieldDeployedDate": "Deployed Date",
    "FieldReturnDate": "Return Date",
    "FieldNotes": "Notes",
    "DeleteDeploymentTitle": "Delete Deployment",
    "DeleteDeploymentMessage": "Are you sure you want to delete this deployment? This action cannot be undone.",
    "LoadingMessage": "Loading data...",
    "LoadingUserMessage": "Loading user profile...",
    "ErrorPrefix": "Error: ",
    "UserErrorPrefix": "Could not load user profile: ",
    "NoAssetsMessage": "No assets found.",
    "NoDeploymentsMessage": "No deployments found for your department."
  }
});
